### ISSUE TITLE
Issue with MaNGA when converting to arrow

### ISSUE THREAD

**Issue by EiffL** [MultimodalUniverse/MultimodalUniverse#100]
@havok2063 I have the following issue with manga which is preventing me from uploading to HF.

The test works but the following doesn't:

```python
import datasets
from datasets import Dataset
from functools import partial

dset = datasets.load_dataset(f'/mnt/ceph/users/polymathic/MultimodalUniverse/manga', 
                    trust_remote_code=True, streaming=True, split='train')

dset = dset.take(5)

def gen_from_iterable_dataset(iterable_ds):
    yield from iterable_ds

ds = Dataset.from_generator(partial(gen_from_iterable_dataset, dset), 
                                    features=dset.features)
```

It doesnt work because the conversion to Arrow is not too happy about the way the data is structured. For spaxels at least I tracked it down to the fact that the flux field and such don't actually have the declared shape of a list of 2d arrays of size (1,N).

The same thing should happen with the tiny version of the dataset if you want to try locally

Could you take a look?

**Comment by mb010** [comment]
This has been fixed with the new manga changes in #129 (tested code above and it passes).
