### ISSUE TITLE
Verification of all datasets

### ISSUE THREAD

**Issue by EiffL** [MultimodalUniverse/MultimodalUniverse#123]
Hi team, 

Ahead of the announcement of the dataset, we want to check that everything works as expected for users. **Please follow the procedure below for the datasets you contributed yourself**, and report any issue you encounter.

## Prodecure

 - Make a copy of this [notebook](https://colab.research.google.com/drive/1axZsf9DcX2XovzE_TSigHG3wiN-MEaFW?usp=sharing)
 - Verify that the notebook works with your dataset.
 - Link it in the list of datasets below.
 - Open an issue for any problem, using the `v1` milestone
 - If all is good, check the checkmark in this issue.

## Datasets:

- [x] apogee ([notebook](https://colab.research.google.com/gist/al-jshen/aa4ce258ab342b30c88cea9ffee5a4be/template-testing-notebook.ipynb), all good, checked by @al-jshen)
- [x] btsbot (*not working* -- BTSbot dataset is not on the HF hub)
- [x] cfa
- [x] chandra
- [x] desi
- [x] desi_provabgs ([notebook](https://colab.research.google.com/drive/1Ad2oD9vSzLD2DDSmUVrWC3_Urjvna05b?usp=sharing), all good, checked by @lhparker1 )
- [x] des_y3_sne_ia ([notebook](https://colab.research.google.com/drive/1zPT3yBIUG7TbwwF5l2hngzdK8uB4LODB?usp=sharing), all good, checked by @benboyd97 )
- [x] foundation ([notebook](https://colab.research.google.com/drive/1hX0eVj0bmfMgAgZ9N1VPI3dgTtFZmnAZ?usp=sharing), all good, checked by @benboyd97 )
- [x] gaia ([notebook](https://colab.research.google.com/gist/al-jshen/71848f160b291fcf370b25cc8c51e140/template-testing-notebook.ipynb) all good, checked by @al-jshen)
- [x] gz10 ([notebook](https://colab.research.google.com/drive/19lfD5T7WPOPk902PAqYZrLDE_4m1Mr4P?usp=sharing), all good, checked by @lhparker1 )
- [x] hsc
- [ ] jwst
- [x] legacysurvey ([notebook](https://colab.research.google.com/drive/1axZsf9DcX2XovzE_TSigHG3wiN-MEaFW?usp=sharing), all good, checked by @EiffL)
- [x] manga
- [x] plasticc
- [x] ps1_sne_ia ([notebook](https://colab.research.google.com/drive/1bpc1ttqtSSf7Orv3pFOsOXwGu9TcvQk2?usp=sharing), all good, checked by @benboyd97 )
- [x] sdss ([notebook](https://colab.research.google.com/drive/1meS3LIiGRgphmW9zd9rDce4Uw5u6sDkV#scrollTo=UYbl9XtwILq4) all good, checked by @lhparker1 )
- [x] snls ([notebook](https://colab.research.google.com/drive/1KbNCnxFnLIGOHPknT08saeuBWcVSCui8?usp=sharing), all good, checked by @benboyd97 )
- [x] ssl_legacysurvey
- [x] swift_sne_ia ([notebook](https://colab.research.google.com/drive/1pcj5iBTr87jNs6_m7007oHRGVkqy2Zhx?usp=sharing), all good, checked by @benboyd97 )
- [x] tess ([notebook](https://colab.research.google.com/drive/1WLlFYkSq4oovEwMOChTVb6IRIcGzpP8S?usp=sharing), all good, checked by @jeraud)
- [x] vipers ([notebook](https://a.research.google.com/drive/1ESBKplXH2rP183NLAvTMsD67N5fd4Zsd#scrollTo=78ronBtftjzM), all good, checked by @lhparker1 )
- [x] yse ([notebook](https://colab.research.google.com/drive/1Cqy1ZPUJ0wCdpi7G03H_GwoR6-KYtRKp?usp=sharing), all good, checked by @benboyd97 )

**Comment by benboyd97** [comment]
The csp dataset is also in the OL but does not exist in the code

**Comment by jeraud** [comment]
> These lightcurve datasets have possible issues:
> 
>     * tess does not have the band field; RA, DEC are capital keys

The TESS light curves are single-band light curves. Hence why there's no band field. Regarding the capital keys: do you mean they should be converted into lower case 'ra' and 'dec'? Or doesn't matter?

**Comment by ado8** [comment]
I believe the reason the CfA datasets were not uploaded to huggingface is because of issue #124.

**Comment by mb010** [comment]
> The csp dataset is also in the OL but does not exist in the code @ado8

@benboyd97 csp has now been merged. 👍 (including some minor changes to cfa, which has to be updated slightly - discussion in #124).
