### ISSUE TITLE
Dataset Compilation Log

### ISSUE THREAD

**Issue by EiffL** [MultimodalUniverse/MultimodalUniverse#75]
I'm going to use this issue to document the export of all the datasets we have on the Flatiron cluster.

All datasets should be available at this link: https://users.flatironinstitute.org/~flanusse/AstroPile_v1/

Datasets listed here should be compatible with the `main` branch at commit version [427b833](https://github.com/AstroPile/AstroPile_prototype/commit/427b833e334b796a0e6d3193181e2276f819efa3), unless noted otherwise.
- [x] apogee **(but got a few NaN warning, and it's only 17 MB?)**
- [x] btsbot (Jeff working on this)
- [x] decals
- [x] desi
- [x] desi_provabgs (Jeff working on this)
- [x] des_y3_sne_ia (Jeff working on this)
- [x] foundation (Jeff working on this)
- [x] gaia **(Jeff working on this)**
- [x] gz10
- [x] hsc **(Francois working on this)**
- [x] jwst
- [x] plasticc
- [x] ps1_sne_ia (Jeff working on this)
- [x] sdss
- [x] snls (Jeff working on this)
- [x] swift_sne_ia (Jeff working on this)
- [x] yse (Jeff working on this)
- [x] vipers
- [x] manga 
- [x] tess (Jeff working on this)
- [x] chandra **(Francois is working on this)**

I'm adding some utilities and fixing production bugs as I go in this branch https://github.com/AstroPile/AstroPile_prototype/tree/compile

**Comment by EiffL** [comment]
@henrysky during APOGEE export, I noticed a few of these message:

```
/mnt/home/flanusse/repo/AstroPile_dev/scripts/apogee/build_parent_sample.py:147: RuntimeWarning: divide by zero encountered in divide
  continuum_ivar = 1 / hdus[2].data ** 2
/mnt/home/flanusse/repo/AstroPile_dev/scripts/apogee/build_parent_sample.py:147: RuntimeWarning: divide by zero encountered in divide
  continuum_ivar = 1 / hdus[2].data ** 2
/mnt/home/flanusse/repo/AstroPile_dev/scripts/apogee/build_parent_sample.py:147: RuntimeWarning: divide by zero encountered in divide
  continuum_ivar = 1 / hdus[2].data ** 2
```

It might be good to prevent NaNs at that initial level, could you take a look?

**Comment by mb010** [comment]
Should chandra be added @EiffL @juramaga ?

**Comment by juramaga** [comment]
I am of course positive about the possibility of including Chandra. We just merged the branch and data looks good from the test.

**Comment by EiffL** [comment]
I've added it to the list :-)

**Comment by juramaga** [comment]
Good. So is the expectation that we download the dataset and put it there? Is there a deadline?

**Comment by EiffL** [comment]
We are taking care of the next step which is donwloading everything at flatiron :-)

**Comment by juramaga** [comment]
I still don't see the Chandra dataset in the flatiron link you provided, @EiffL . Let me know if there are any issues.
